name: cluster_server
services:
  backend_1:
    image: backend_python:latest
    container_name: cluster_backend_1

    networks:
      cluster_net:
        ipv4_address: 20.1.0.5

  backend_2:
    image: backend_python:latest
    container_name: cluster_backend_2

    networks:
      cluster_net:
        ipv4_address: 20.1.0.7
  backend_3:
    image: backend_python:latest
    container_name: cluster_backend_3

    networks:
      cluster_net:
        ipv4_address: 20.1.0.9

  backend_4:
    image: backend_python:latest
    container_name: cluster_backend_4

    networks:
      cluster_net:
        ipv4_address: 20.1.0.11

  ingress:
    image: nginx:latest
    ports:
      - 5000:90
    depends_on:
      - backend_1
      - backend_2
      - backend_3
      - backend_4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    


networks:
  cluster_net:
    driver: bridge
    ipam:
      config:
        - subnet: 20.1.0.0/16
          gateway: 20.1.0.1